function s=construct1d(varargin)

switch nargin
  case 0
    s = struct('freq',[],...
      'time',[],...
      't1',[],...
      'w1',[],...
      'R1',[],...
      'R',[],...
      'phase',[],...
      'S_noise',[],...
      'basename',[],...
      'undersampling',[],...
      'centerfreq',[],...
      'resolution',[],...
      'zeropad',[],...
      'time_units',[],...
      'freq_units',[],...
      'spec_calib',[],...
      'pump_probe',[],...
      'pump_probe_freq',[],...
      'comment',[]);
  case 1
    if isa(varargin{1},'struct')
      s = varargin{1};
    else
      error('Construct2d wrong argument type');
    end
end
