function s = contstruct3d

s = struct('freq',[],...
  'time',[],...
  't2',[],...
  't4',[],...
  't5',[],...
  'w1',[],...
  'w3',[],...
  'w5',[],...
  'R',[],...
  'R1',[],...
  'R2',[],...
  'R3',[],...
  'R4',[],...
  'phase',[],...
  'R1_noise',[],...
  'R2_noise',[],...  
  'R3_noise',[],...  
  'R4_noise',[],...
  'basename',[],...
  'undersampling',[],...
  'centerfreq',[],...
  'resolution',[],...
  'zeropad',[],...
  'time_units',[],...
  'freq_units',[],...
  'spec_calib',[],...
  'comment',[]);
