function output = sort2DIRdata(input)
% SORT2DIRDATA sorts (from low to high t2) and compresses a 2D-IR data
% similar to that generated by LOAD2DIRDATA. Normal syntax, which will
% overwrite the old data structure, is:
%
%      data = sort2DIRdata(data);
%
% Most of the scripts I've written require sorted data.
%
% TO DO: EXPAND THIS TO ALLOW YOU TO SORT BY AN ARBITRARY FIELD

empty_elems = arrayfun(@(s) all(structfun(@isempty,s)),input);
temp = input(~empty_elems);
uh = [temp.t2];
[~,ind] = sort(uh);
output = temp(ind);